### ISSUE TITLE
Problème en utilisant le model TaskResult de Django-celeris-result.

### ISSUE THREAD

**Issue by enzofrnt** [Horou/djangorestframework-deepserializer#2]
Mon code :
```python
class TaskInfo(models.Model):
    task_id = models.ForeignKey('TaskResult', on_delete=models.CASCADE, to_field='task_id') 
    task_name = models.CharField(max_length=255)
    sbom = models.ForeignKey('Sboms', on_delete=models.CASCADE, to_field='PathSbom', related_name='task_infos')
    
class Sboms(models.Model):
    idSbom = models.AutoField(primary_key=True)
    PathSbom = models.CharField(max_length=200, unique=True)
    
 #La class Task
```

Code du model provenant de Django-celeris-result.
[ici](https://github.com/celery/django-celery-results/blob/main/django_celery_results/models.py)
```python
"""Database models."""

import json

from celery import states
from celery.result import GroupResult as CeleryGroupResult
from celery.result import result_from_tuple
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

from . import managers

ALL_STATES = sorted(states.ALL_STATES)
TASK_STATE_CHOICES = sorted(zip(ALL_STATES, ALL_STATES))


class TaskResult(models.Model):
    """Task result/status."""

    task_id = models.CharField(
        max_length=getattr(
            settings,
            'DJANGO_CELERY_RESULTS_TASK_ID_MAX_LENGTH',
            255
        ),
        unique=True,
        verbose_name=_('Task ID'),
        help_text=_('Celery ID for the Task that was run'))
    periodic_task_name = models.CharField(
        null=True, max_length=255,
        verbose_name=_('Periodic Task Name'),
        help_text=_('Name of the Periodic Task which was run'))
    task_name = models.CharField(
        null=True, max_length=getattr(
            settings,
            'DJANGO_CELERY_RESULTS_TASK_ID_MAX_LENGTH',
            255
        ),
        verbose_name=_('Task Name'),
        help_text=_('Name of the Task which was run'))
    task_args = models.TextField(
        null=True,
        verbose_name=_('Task Positional Arguments'),
        help_text=_('JSON representation of the positional arguments '
                    'used with the task'))
    task_kwargs = models.TextField(
        null=True,
        verbose_name=_('Task Named Arguments'),
        help_text=_('JSON representation of the named arguments '
                    'used with the task'))
    status = models.CharField(
        max_length=50, default=states.PENDING,
        choices=TASK_STATE_CHOICES,
        verbose_name=_('Task State'),
        help_text=_('Current state of the task being run'))
    worker = models.CharField(
        max_length=100, default=None, null=True,
        verbose_name=_('Worker'), help_text=_('Worker that executes the task')
    )
    content_type = models.CharField(
        max_length=128,
        verbose_name=_('Result Content Type'),
        help_text=_('Content type of the result data'))
    content_encoding = models.CharField(
        max_length=64,
        verbose_name=_('Result Encoding'),
        help_text=_('The encoding used to save the task result data'))
    result = models.TextField(
        null=True, default=None, editable=False,
        verbose_name=_('Result Data'),
        help_text=_('The data returned by the task.  '
                    'Use content_encoding and content_type fields to read.'))
    date_created = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('Created DateTime'),
        help_text=_('Datetime field when the task result was created in UTC'))
    date_done = models.DateTimeField(
        auto_now=True,
        verbose_name=_('Completed DateTime'),
        help_text=_('Datetime field when the task was completed in UTC'))
    traceback = models.TextField(
        blank=True, null=True,
        verbose_name=_('Traceback'),
        help_text=_('Text of the traceback if the task generated one'))
    meta = models.TextField(
        null=True, default=None, editable=False,
        verbose_name=_('Task Meta Information'),
        help_text=_('JSON meta information about the task, '
                    'such as information on child tasks'))

    objects = managers.TaskResultManager()

    class Meta:
        """Table information."""

        ordering = ['-date_done']

        verbose_name = _('task result')
        verbose_name_plural = _('task results')

        # Explicit names to solve https://code.djangoproject.com/ticket/33483
        indexes = [
            models.Index(fields=['task_name'],
                         name='django_cele_task_na_08aec9_idx'),
            models.Index(fields=['status'],
                         name='django_cele_status_9b6201_idx'),
            models.Index(fields=['worker'],
                         name='django_cele_worker_d54dd8_idx'),
            models.Index(fields=['date_created'],
                         name='django_cele_date_cr_f04a50_idx'),
            models.Index(fields=['date_done'],
                         name='django_cele_date_do_f59aad_idx'),
        ]

    def as_dict(self):
        return {
            'task_id': self.task_id,
            'task_name': self.task_name,
            'task_args': self.task_args,
            'task_kwargs': self.task_kwargs,
            'status': self.status,
            'result': self.result,
            'date_done': self.date_done,
            'traceback': self.traceback,
            'meta': self.meta,
            'worker': self.worker
        }

    def __str__(self):
        return '<Task: {0.task_id} ({0.status})>'.format(self)


class ChordCounter(models.Model):
    """Chord synchronisation."""

    group_id = models.CharField(
        max_length=getattr(
            settings,
            "DJANGO_CELERY_RESULTS_TASK_ID_MAX_LENGTH",
            255),
        unique=True,
        verbose_name=_("Group ID"),
        help_text=_("Celery ID for the Chord header group"),
    )
    sub_tasks = models.TextField(
        help_text=_(
            "JSON serialized list of task result tuples. "
            "use .group_result() to decode"
        )
    )
    count = models.PositiveIntegerField(
        help_text=_(
            "Starts at len(chord header) and decrements after each task is "
            "finished"
        )
    )

    def group_result(self, app=None):
        """Return the :class:`celery.result.GroupResult` of self.

        Arguments:
            app (celery.app.base.Celery): app instance to create the
               :class:`celery.result.GroupResult` with.

        """
        return CeleryGroupResult(
            self.group_id,
            [result_from_tuple(r, app=app)
             for r in json.loads(self.sub_tasks)],
            app=app
        )


class GroupResult(models.Model):
    """Task Group result/status."""

    group_id = models.CharField(
        max_length=getattr(
            settings,
            "DJANGO_CELERY_RESULTS_TASK_ID_MAX_LENGTH",
            255
        ),
        unique=True,
        verbose_name=_("Group ID"),
        help_text=_("Celery ID for the Group that was run"),
    )
    date_created = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("Created DateTime"),
        help_text=_("Datetime field when the group result was created in UTC"),
    )
    date_done = models.DateTimeField(
        auto_now=True,
        verbose_name=_("Completed DateTime"),
        help_text=_("Datetime field when the group was completed in UTC"),
    )
    content_type = models.CharField(
        max_length=128,
        verbose_name=_("Result Content Type"),
        help_text=_("Content type of the result data"),
    )
    content_encoding = models.CharField(
        max_length=64,
        verbose_name=_("Result Encoding"),
        help_text=_("The encoding used to save the task result data"),
    )
    result = models.TextField(
        null=True, default=None, editable=False,
        verbose_name=_('Result Data'),
        help_text=_('The data returned by the task.  '
                    'Use content_encoding and content_type fields to read.'))

    def as_dict(self):
        return {
            'group_id': self.group_id,
            'result': self.result,
            'date_done': self.date_done,
        }

    def __str__(self):
        return f'<Group: {self.group_id}>'

    objects = managers.GroupResultManager()

    class Meta:
        """Table information."""

        ordering = ['-date_done']

        verbose_name = _('group result')
        verbose_name_plural = _('group results')

        # Explicit names to solve https://code.djangoproject.com/ticket/33483
        indexes = [
            models.Index(fields=['date_created'],
                         name='django_cele_date_cr_bd6c1d_idx'),
            models.Index(fields=['date_done'],
                         name='django_cele_date_do_caae0e_idx'),
        ]
```

Erreur :
```python
Traceback (most recent call last):
  File "/back-end/manage.py", line 22, in <module>
    main()
  File "/back-end/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.11/site-packages/django/core/management/base.py", line 454, in execute
    self.check()
  File "/usr/lib/python3.11/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/django/urls/resolvers.py", line 519, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/back-end/project/urls.py", line 25, in <module>
    from app.views import UploadProductViewSet, UploadVersionViewSet, get_APIConfig, TaskResultView
  File "/back-end/app/views/__init__.py", line 1, in <module>
    from .uploadsbominversionview import UploadVersionViewSet, UploadProductViewSet
  File "/back-end/app/views/uploadsbominversionview.py", line 125, in <module>
    class UploadVersionViewSet(DeepViewSet):
  File "/usr/lib/python3.11/site-packages/deepserializer/views.py", line 35, in __init_subclass__
    cls._possible_fields = cls.build_possible_fields(model, [])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deepserializer/views.py", line 58, in build_possible_fields
    for field in cls.build_possible_fields(model, excludes + [parent_model])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deepserializer/views.py", line 58, in build_possible_fields
    for field in cls.build_possible_fields(model, excludes + [parent_model])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deepserializer/views.py", line 58, in build_possible_fields
    for field in cls.build_possible_fields(model, excludes + [parent_model])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deepserializer/views.py", line 51, in build_possible_fields
    for field_relation in parent_model._meta.get_fields():
                          ^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute '_meta'
```

**Comment by enzofrnt** [comment]
Lorsque je retire la ligne :
```python
task_id = models.ForeignKey('TaskResult', on_delete=models.CASCADE, to_field='task_id') 
```
L'erreur disparait.

**Comment by enzofrnt** [comment]
Il semblerait que puisque le model n'est pas présent dans mon app mais dans le module `django-celery-result`, il faille importer le model et l'ajouter directement et pas via une `String`.
```python
from django_celery_results.models import TaskResult #Correction

class TaskInfo(models.Model):
    class Meta:
        unique_together = ('task_id', 'sbom')

    task_id = models.ForeignKey(TaskResult, on_delete=models.CASCADE, to_field='task_id') 
                    #Correction ^^^^^^^^^^
    task_name = models.CharField(max_length=255)
    sbom = models.ForeignKey('Sboms', on_delete=models.CASCADE, to_field='PathSbom', related_name='task_infos')
```
    
Je n'ai pas encore vérifié si la migration et le remplissage de la BD fonctionne.
Correctement.

**Comment by Horou** [comment]
le problème vient de la résolution du model 'TaskResult' vers TaskResult, je cherche une solution, 
pour le moment tu peut écrire:
task_id = models.ForeignKey(TaskResult, on_delete=models.CASCADE, to_field='task_id')
ça devrais marché

**Comment by Horou** [comment]
j'ai trouvé une solution, j'ai fais une modif sur le deepserializer/views.py, tu as juste a copié, dis moi si ça marche, si ça marche on pourra faire une nouvelle version.

**Comment by enzofrnt** [comment]
> j'ai trouvé une solution, j'ai fais une modif sur le deepserializer/views.py, tu as juste a copié, dis moi si ça marche, si ça marche on pourra faire une nouvelle version.

Je vais tester, mais ne t'inquiète pas, je ferrai moi-même une nouvelle version si nécessaire.

**Comment by enzofrnt** [comment]
> j'ai trouvé une solution, j'ai fais une modif sur le deepserializer/views.py, tu as juste a copié, dis moi si ça marche, si ça marche on pourra faire une nouvelle version.

Je pense que tu peux annuler t'as modif :
```python
/usr/lib/python3.11/site-packages/deepserializer # api
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/django/apps/config.py", line 235, in get_model
    return self.models[model_name.lower()]
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'taskresult'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/back-end/manage.py", line 22, in <module>
    main()
  File "/back-end/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.11/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.11/site-packages/django/core/management/base.py", line 454, in execute
    self.check()
  File "/usr/lib/python3.11/site-packages/django/core/management/base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/django/core/checks/urls.py", line 42, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/django/core/checks/urls.py", line 61, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/django/urls/resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/django/urls/resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/back-end/project/urls.py", line 25, in <module>
    from app.views import UploadProductViewSet, UploadVersionViewSet, get_APIConfig, TaskResultView
  File "/back-end/app/views/__init__.py", line 1, in <module>
    from .uploadsbominversionview import UploadVersionViewSet, UploadProductViewSet
  File "/back-end/app/views/uploadsbominversionview.py", line 125, in <module>
    class UploadVersionViewSet(DeepViewSet):
  File "/usr/lib/python3.11/site-packages/deepserializer/views.py", line 36, in __init_subclass__
    cls._possible_fields = cls.build_possible_fields(model, [])
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deepserializer/views.py", line 61, in build_possible_fields
    for field in cls.build_possible_fields(model, excludes + [parent_model])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deepserializer/views.py", line 61, in build_possible_fields
    for field in cls.build_possible_fields(model, excludes + [parent_model])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/deepserializer/views.py", line 54, in build_possible_fields
    model = apps.get_model(app_label, tmp_model) if isinstance(tmp_model, str) else tmp_model
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/django/apps/registry.py", line 213, in get_model
    return app_config.get_model(model_name, require_ready=require_ready)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/django/apps/config.py", line 237, in get_model
    raise LookupError(
LookupError: App 'app' doesn't have a 'TaskResult' model.
```

La model que j'utilise n'existe pas dans mon app, il est dans un autre module, je pense que la meilleure solution, c'est de documenter le fait que si un model utiliser ne fait pas partie intégrante de l'application courante. On peut importer le module comme je le montre ici et comme tu me l'as suggéré :
```python
from django_celery_results.models import TaskResult #Correction

class TaskInfo(models.Model):
    class Meta:
        unique_together = ('task_id', 'sbom')

    task_id = models.ForeignKey(TaskResult, on_delete=models.CASCADE, to_field='task_id') 
                    #Correction ^^^^^^^^^^
    task_name = models.CharField(max_length=255)
    sbom = models.ForeignKey('Sboms', on_delete=models.CASCADE, to_field='PathSbom', related_name='task_infos')
```

Sans risque une erreur d'importation circulaire ou autre…

Mais je vais d'abord vérifier que c'est fonctionnel ;)

**Comment by Horou** [comment]
j'avais pas compris, je pensais que TaskResult était un model écrit par toi qui hérité d'un model de django_celery_results, l'écriture correct pour ce cas c'est comme tu l'a mis dans ton exemple précèdent.

**Comment by Horou** [comment]
En django, les import par str a la place de la classe c'est uniquement si il y a un problème d'import circulaire.
